export type Rarity = 'Common' | 'Uncommon' | 'Rare' | 'Epic' | 'Legendary' | 'Mythic' | 'Ultra Mythic';
export type Season = 'New Genesis' | 'Video Game';

export interface Card {
  id: string;
  name: string;
  rarity: Rarity;
  color: string;
  season: Season;
}

export const RARITIES: Record<Rarity, { chance: number; color: string; bg: string; glow: string; dropRate: string }> = {
  'Common': { chance: 0.60, color: '#94a3b8', bg: 'bg-zinc-800', glow: 'shadow-zinc-500/20', dropRate: '1.5% each' },
  'Uncommon': { chance: 0.25, color: '#4ade80', bg: 'bg-emerald-900', glow: 'shadow-emerald-500/30', dropRate: '1.0% each' },
  'Rare': { chance: 0.0795, color: '#60a5fa', bg: 'bg-blue-900', glow: 'shadow-blue-500/40', dropRate: '0.53% each' },
  'Epic': { chance: 0.040, color: '#c084fc', bg: 'bg-purple-900', glow: 'shadow-purple-500/50', dropRate: '0.40% each' },
  'Legendary': { chance: 0.0198, color: '#fbbf24', bg: 'bg-amber-900', glow: 'shadow-amber-500/60', dropRate: '0.33% each' },
  'Mythic': { chance: 0.0090, color: '#f87171', bg: 'bg-red-900', glow: 'shadow-red-500/70', dropRate: '0.30% each' },
  'Ultra Mythic': { chance: 0.0010, color: '#ffffff', bg: 'bg-white', glow: 'shadow-white/80', dropRate: '0.10% each' },
};

export const ALL_CARDS: Card[] = [
  // --- NEW GENESIS SEASON ---
  // Common (40)
  { id: 'pebble-scout', name: 'Pebble Scout', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'mossling-gatherer', name: 'Mossling Gatherer', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'driftwood-golem', name: 'Driftwood Golem', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'sand-sprinter', name: 'Sand Sprinter', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'coral-bug', name: 'Coral Bug', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'fog-crawler', name: 'Fog Crawler', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'ember-twig', name: 'Ember Twig', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'brook-minnow', name: 'Brook Minnow', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'stone-tortoise', name: 'Stone Tortoise', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'windleaf-sprite', name: 'Windleaf Sprite', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'dust-hopper', name: 'Dust Hopper', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'vine-snare', name: 'Vine Snare', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'crag-rat', name: 'Crag Rat', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'tide-skipper', name: 'Tide Skipper', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'barkhide-lizard', name: 'Barkhide Lizard', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'glow-ant', name: 'Glow Ant', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'hollow-beetle', name: 'Hollow Beetle', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'rain-drifter', name: 'Rain Drifter', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'mud-slug', name: 'Mud Slug', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'sunseed-imp', name: 'Sunseed Imp', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'cliff-roamer', name: 'Cliff Roamer', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'frost-petal', name: 'Frost Petal', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'thorn-pup', name: 'Thorn Pup', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'echo-sparrow', name: 'Echo Sparrow', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'river-pebbler', name: 'River Pebbler', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'ash-mite', name: 'Ash Mite', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'bramble-mouse', name: 'Bramble Mouse', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'gale-feather', name: 'Gale Feather', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'root-creeper', name: 'Root Creeper', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'dune-hopper', name: 'Dune Hopper', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'cloudlet', name: 'Cloudlet', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'sapling-guard', name: 'Sapling Guard', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'flame-flicker', name: 'Flame Flicker', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'ice-shardling', name: 'Ice Shardling', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'shale-worm', name: 'Shale Worm', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'night-cricket', name: 'Night Cricket', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'bloom-pixie', name: 'Bloom Pixie', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'drift-seed', name: 'Drift Seed', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'ember-dust', name: 'Ember Dust', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  { id: 'shellback-crab', name: 'Shellback Crab', rarity: 'Common', color: '#94a3b8', season: 'New Genesis' },
  // Uncommon (25)
  { id: 'thornhide-boar', name: 'Thornhide Boar', rarity: 'Uncommon', color: '#4ade80', season: 'New Genesis' },
  { id: 'crystal-finch', name: 'Crystal Finch', rarity: 'Uncommon', color: '#4ade80', season: 'New Genesis' },
  { id: 'wavecaller-adept', name: 'Wavecaller Adept', rarity: 'Uncommon', color: '#4ade80', season: 'New Genesis' },
  { id: 'ember-fox', name: 'Ember Fox', rarity: 'Uncommon', color: '#4ade80', season: 'New Genesis' },
  { id: 'ironroot-treant', name: 'Ironroot Treant', rarity: 'Uncommon', color: '#4ade80', season: 'New Genesis' },
  { id: 'frosttail-lynx', name: 'Frosttail Lynx', rarity: 'Uncommon', color: '#4ade80', season: 'New Genesis' },
  { id: 'sandstorm-adept', name: 'Sandstorm Adept', rarity: 'Uncommon', color: '#4ade80', season: 'New Genesis' },
  { id: 'glowvine-witch', name: 'Glowvine Witch', rarity: 'Uncommon', color: '#4ade80', season: 'New Genesis' },
  { id: 'storm-kite', name: 'Storm Kite', rarity: 'Uncommon', color: '#4ade80', season: 'New Genesis' },
  { id: 'lava-hopper', name: 'Lava Hopper', rarity: 'Uncommon', color: '#4ade80', season: 'New Genesis' },
  { id: 'coral-knight', name: 'Coral Knight', rarity: 'Uncommon', color: '#4ade80', season: 'New Genesis' },
  { id: 'mist-stalker', name: 'Mist Stalker', rarity: 'Uncommon', color: '#4ade80', season: 'New Genesis' },
  { id: 'windblade-hawk', name: 'Windblade Hawk', rarity: 'Uncommon', color: '#4ade80', season: 'New Genesis' },
  { id: 'ashen-wolf', name: 'Ashen Wolf', rarity: 'Uncommon', color: '#4ade80', season: 'New Genesis' },
  { id: 'stoneguard-sentinel', name: 'Stoneguard Sentinel', rarity: 'Uncommon', color: '#4ade80', season: 'New Genesis' },
  { id: 'river-serpent', name: 'River Serpent', rarity: 'Uncommon', color: '#4ade80', season: 'New Genesis' },
  { id: 'bloom-shaman', name: 'Bloom Shaman', rarity: 'Uncommon', color: '#4ade80', season: 'New Genesis' },
  { id: 'dune-seraph', name: 'Dune Seraph', rarity: 'Uncommon', color: '#4ade80', season: 'New Genesis' },
  { id: 'flame-dancer', name: 'Flame Dancer', rarity: 'Uncommon', color: '#4ade80', season: 'New Genesis' },
  { id: 'icebound-archer', name: 'Icebound Archer', rarity: 'Uncommon', color: '#4ade80', season: 'New Genesis' },
  { id: 'thunder-cub', name: 'Thunder Cub', rarity: 'Uncommon', color: '#4ade80', season: 'New Genesis' },
  { id: 'nightshade-rogue', name: 'Nightshade Rogue', rarity: 'Uncommon', color: '#4ade80', season: 'New Genesis' },
  { id: 'sunflare-monk', name: 'Sunflare Monk', rarity: 'Uncommon', color: '#4ade80', season: 'New Genesis' },
  { id: 'rootbinder-mage', name: 'Rootbinder Mage', rarity: 'Uncommon', color: '#4ade80', season: 'New Genesis' },
  { id: 'gale-rider', name: 'Gale Rider', rarity: 'Uncommon', color: '#4ade80', season: 'New Genesis' },
  // Rare (15)
  { id: 'stormforge-golem', name: 'Stormforge Golem', rarity: 'Rare', color: '#60a5fa', season: 'New Genesis' },
  { id: 'frostbrand-warrior', name: 'Frostbrand Warrior', rarity: 'Rare', color: '#60a5fa', season: 'New Genesis' },
  { id: 'emberclaw-tiger', name: 'Emberclaw Tiger', rarity: 'Rare', color: '#60a5fa', season: 'New Genesis' },
  { id: 'tidebreaker-giant', name: 'Tidebreaker Giant', rarity: 'Rare', color: '#60a5fa', season: 'New Genesis' },
  { id: 'thornqueen-dryad', name: 'Thornqueen Dryad', rarity: 'Rare', color: '#60a5fa', season: 'New Genesis' },
  { id: 'skybreaker-griffin', name: 'Skybreaker Griffin', rarity: 'Rare', color: '#60a5fa', season: 'New Genesis' },
  { id: 'lava-titan', name: 'Lava Titan', rarity: 'Rare', color: '#60a5fa', season: 'New Genesis' },
  { id: 'crystal-sage', name: 'Crystal Sage', rarity: 'Rare', color: '#60a5fa', season: 'New Genesis' },
  { id: 'nightfall-assassin', name: 'Nightfall Assassin', rarity: 'Rare', color: '#60a5fa', season: 'New Genesis' },
  { id: 'sunblade-paladin', name: 'Sunblade Paladin', rarity: 'Rare', color: '#60a5fa', season: 'New Genesis' },
  { id: 'ironclad-juggernaut', name: 'Ironclad Juggernaut', rarity: 'Rare', color: '#60a5fa', season: 'New Genesis' },
  { id: 'windstorm-dragonet', name: 'Windstorm Dragonet', rarity: 'Rare', color: '#60a5fa', season: 'New Genesis' },
  { id: 'dunestrider-champion', name: 'Dunestrider Champion', rarity: 'Rare', color: '#60a5fa', season: 'New Genesis' },
  { id: 'bloom-guardian', name: 'Bloom Guardian', rarity: 'Rare', color: '#60a5fa', season: 'New Genesis' },
  { id: 'shadowveil-sorcerer', name: 'Shadowveil Sorcerer', rarity: 'Rare', color: '#60a5fa', season: 'New Genesis' },
  // Epic (10)
  { id: 'inferno-phoenix', name: 'Inferno Phoenix', rarity: 'Epic', color: '#c084fc', season: 'New Genesis' },
  { id: 'glacier-colossus', name: 'Glacier Colossus', rarity: 'Epic', color: '#c084fc', season: 'New Genesis' },
  { id: 'tempest-leviathan', name: 'Tempest Leviathan', rarity: 'Epic', color: '#c084fc', season: 'New Genesis' },
  { id: 'verdant-overlord', name: 'Verdant Overlord', rarity: 'Epic', color: '#c084fc', season: 'New Genesis' },
  { id: 'eclipse-harbinger', name: 'Eclipse Harbinger', rarity: 'Epic', color: '#c084fc', season: 'New Genesis' },
  { id: 'thunderlord-behemoth', name: 'Thunderlord Behemoth', rarity: 'Epic', color: '#c084fc', season: 'New Genesis' },
  { id: 'starfall-enchanter', name: 'Starfall Enchanter', rarity: 'Epic', color: '#c084fc', season: 'New Genesis' },
  { id: 'abyssal-warden', name: 'Abyssal Warden', rarity: 'Epic', color: '#c084fc', season: 'New Genesis' },
  { id: 'solar-archangel', name: 'Solar Archangel', rarity: 'Epic', color: '#c084fc', season: 'New Genesis' },
  { id: 'voidblade-executioner', name: 'Voidblade Executioner', rarity: 'Epic', color: '#c084fc', season: 'New Genesis' },
  // Legendary (6)
  { id: 'ignivar', name: 'Ignivar, Flame Sovereign', rarity: 'Legendary', color: '#fbbf24', season: 'New Genesis' },
  { id: 'cryonix', name: 'Cryonix, Lord of Frost', rarity: 'Legendary', color: '#fbbf24', season: 'New Genesis' },
  { id: 'zephyros', name: 'Zephyros, Sky Tyrant', rarity: 'Legendary', color: '#fbbf24', season: 'New Genesis' },
  { id: 'terradon', name: 'Terradon, Earthbreaker', rarity: 'Legendary', color: '#fbbf24', season: 'New Genesis' },
  { id: 'lumina', name: 'Lumina, Radiant Queen', rarity: 'Legendary', color: '#fbbf24', season: 'New Genesis' },
  { id: 'umbros', name: 'Umbros, Shadow King', rarity: 'Legendary', color: '#fbbf24', season: 'New Genesis' },
  // Mythic (3)
  { id: 'aetherion', name: 'Aetherion, Weaver of Realities', rarity: 'Mythic', color: '#f87171', season: 'New Genesis' },
  { id: 'chronaros', name: 'Chronaros, Time Devourer', rarity: 'Mythic', color: '#f87171', season: 'New Genesis' },
  { id: 'nyxara', name: 'Nyxara, Empress of the Void', rarity: 'Mythic', color: '#f87171', season: 'New Genesis' },
  // Ultra Mythic (1)
  { id: 'omnirex', name: 'Omnirex, The Infinite Origin', rarity: 'Ultra Mythic', color: '#ffffff', season: 'New Genesis' },

  // --- VIDEO GAME SEASON ---
  // Common (40)
  { id: 'mario', name: 'Mario', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'sonic-the-hedgehog', name: 'Sonic the Hedgehog', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'steve', name: 'Steve', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'crash-bandicoot', name: 'Crash Bandicoot', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'link', name: 'Link', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'pikachu', name: 'Pikachu', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'mega-man', name: 'Mega Man', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'pac-man', name: 'Pac-Man', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'kirby', name: 'Kirby', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'ryu', name: 'Ryu', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'luigi', name: 'Luigi', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'tails', name: 'Tails', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'alex', name: 'Alex', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'coco-bandicoot', name: 'Coco Bandicoot', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'eevee', name: 'Eevee', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'chun-li', name: 'Chun-Li', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'donkey-kong', name: 'Donkey Kong', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'spyro', name: 'Spyro', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'bomberman', name: 'Bomberman', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'yoshi', name: 'Yoshi', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'knuckles', name: 'Knuckles', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'creeper', name: 'Creeper', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'enderman', name: 'Enderman', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'sora', name: 'Sora', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'toad', name: 'Toad', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'shadow-the-hedgehog', name: 'Shadow the Hedgehog', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'villager', name: 'Villager', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'inkling', name: 'Inkling', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'isabelle', name: 'Isabelle', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'tom-nook', name: 'Tom Nook', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'shovel-knight', name: 'Shovel Knight', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'cuphead', name: 'Cuphead', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'mugman', name: 'Mugman', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'rayman', name: 'Rayman', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'diddy-kong', name: 'Diddy Kong', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'banjo', name: 'Banjo', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'kazooie', name: 'Kazooie', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'sans', name: 'Sans', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'papyrus', name: 'Papyrus', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },
  { id: 'jigglypuff', name: 'Jigglypuff', rarity: 'Common', color: '#94a3b8', season: 'Video Game' },

  // Uncommon (25)
  { id: 'samus-aran', name: 'Samus Aran', rarity: 'Uncommon', color: '#4ade80', season: 'Video Game' },
  { id: 'captain-falcon', name: 'Captain Falcon', rarity: 'Uncommon', color: '#4ade80', season: 'Video Game' },
  { id: 'pit', name: 'Pit', rarity: 'Uncommon', color: '#4ade80', season: 'Video Game' },
  { id: 'marth', name: 'Marth', rarity: 'Uncommon', color: '#4ade80', season: 'Video Game' },
  { id: 'ike', name: 'Ike', rarity: 'Uncommon', color: '#4ade80', season: 'Video Game' },
  { id: 'little-mac', name: 'Little Mac', rarity: 'Uncommon', color: '#4ade80', season: 'Video Game' },
  { id: 'greninja', name: 'Greninja', rarity: 'Uncommon', color: '#4ade80', season: 'Video Game' },
  { id: 'lucario', name: 'Lucario', rarity: 'Uncommon', color: '#4ade80', season: 'Video Game' },
  { id: 'master-chief', name: 'Master Chief', rarity: 'Uncommon', color: '#4ade80', season: 'Video Game' },
  { id: 'scorpion', name: 'Scorpion', rarity: 'Uncommon', color: '#4ade80', season: 'Video Game' },
  { id: 'sub-zero', name: 'Sub-Zero', rarity: 'Uncommon', color: '#4ade80', season: 'Video Game' },
  { id: 'raiden', name: 'Raiden', rarity: 'Uncommon', color: '#4ade80', season: 'Video Game' },
  { id: 'liu-kang', name: 'Liu Kang', rarity: 'Uncommon', color: '#4ade80', season: 'Video Game' },
  { id: 'lara-croft', name: 'Lara Croft', rarity: 'Uncommon', color: '#4ade80', season: 'Video Game' },
  { id: 'nathan-drake', name: 'Nathan Drake', rarity: 'Uncommon', color: '#4ade80', season: 'Video Game' },
  { id: 'sackboy', name: 'Sackboy', rarity: 'Uncommon', color: '#4ade80', season: 'Video Game' },
  { id: 'astro-bot', name: 'Astro Bot', rarity: 'Uncommon', color: '#4ade80', season: 'Video Game' },
  { id: 'ratchet', name: 'Ratchet', rarity: 'Uncommon', color: '#4ade80', season: 'Video Game' },
  { id: 'clank', name: 'Clank', rarity: 'Uncommon', color: '#4ade80', season: 'Video Game' },
  { id: 'jak', name: 'Jak', rarity: 'Uncommon', color: '#4ade80', season: 'Video Game' },
  { id: 'daxter', name: 'Daxter', rarity: 'Uncommon', color: '#4ade80', season: 'Video Game' },
  { id: 'meta-knight', name: 'Meta Knight', rarity: 'Uncommon', color: '#4ade80', season: 'Video Game' },
  { id: 'king-dedede', name: 'King Dedede', rarity: 'Uncommon', color: '#4ade80', season: 'Video Game' },
  { id: 'falco-lombardi', name: 'Falco Lombardi', rarity: 'Uncommon', color: '#4ade80', season: 'Video Game' },
  { id: 'wario', name: 'Wario', rarity: 'Uncommon', color: '#4ade80', season: 'Video Game' },

  // Rare (15)
  { id: 'princess-zelda-breath-of-the-wild', name: 'Princess Zelda (Breath of the Wild)', rarity: 'Rare', color: '#60a5fa', season: 'Video Game' },
  { id: 'king-k-rool', name: 'King K. Rool', rarity: 'Rare', color: '#60a5fa', season: 'Video Game' },
  { id: 'dr-mario', name: 'Dr. Mario', rarity: 'Rare', color: '#60a5fa', season: 'Video Game' },
  { id: 'metal-sonic', name: 'Metal Sonic', rarity: 'Rare', color: '#60a5fa', season: 'Video Game' },
  { id: 'amy-rose', name: 'Amy Rose', rarity: 'Rare', color: '#60a5fa', season: 'Video Game' },
  { id: 'blaze-the-cat', name: 'Blaze the Cat', rarity: 'Rare', color: '#60a5fa', season: 'Video Game' },
  { id: 'charmander', name: 'Charmander', rarity: 'Rare', color: '#60a5fa', season: 'Video Game' },
  { id: 'squirtle', name: 'Squirtle', rarity: 'Rare', color: '#60a5fa', season: 'Video Game' },
  { id: 'bulbasaur', name: 'Bulbasaur', rarity: 'Rare', color: '#60a5fa', season: 'Video Game' },
  { id: 'slime', name: 'Slime', rarity: 'Rare', color: '#60a5fa', season: 'Video Game' },
  { id: 'solid-snake', name: 'Solid Snake', rarity: 'Rare', color: '#60a5fa', season: 'Video Game' },
  { id: 'toon-link', name: 'Toon Link', rarity: 'Rare', color: '#60a5fa', season: 'Video Game' },
  { id: 'mr-game-watch', name: 'Mr. Game & Watch', rarity: 'Rare', color: '#60a5fa', season: 'Video Game' },
  { id: 'doom-slayer', name: 'Doom Slayer', rarity: 'Rare', color: '#60a5fa', season: 'Video Game' },
  { id: 'pichu', name: 'Pichu', rarity: 'Rare', color: '#60a5fa', season: 'Video Game' },

  // Epic (10)
  { id: 'ganondorf', name: 'Ganondorf', rarity: 'Epic', color: '#c084fc', season: 'Video Game' },
  { id: 'bowser', name: 'Bowser', rarity: 'Epic', color: '#c084fc', season: 'Video Game' },
  { id: 'dr-eggman', name: 'Dr. Eggman', rarity: 'Epic', color: '#c084fc', season: 'Video Game' },
  { id: 'm-bison', name: 'M. Bison', rarity: 'Epic', color: '#c084fc', season: 'Video Game' },
  { id: 'akuma', name: 'Akuma', rarity: 'Epic', color: '#c084fc', season: 'Video Game' },
  { id: 'vergil', name: 'Vergil', rarity: 'Epic', color: '#c084fc', season: 'Video Game' },
  { id: 'dante', name: 'Dante', rarity: 'Epic', color: '#c084fc', season: 'Video Game' },
  { id: 'bayonetta', name: 'Bayonetta', rarity: 'Epic', color: '#c084fc', season: 'Video Game' },
  { id: 'ridley', name: 'Ridley', rarity: 'Epic', color: '#c084fc', season: 'Video Game' },
  { id: 'ganon-beast-form', name: 'Ganon (Beast Form)', rarity: 'Epic', color: '#c084fc', season: 'Video Game' },

  // Legendary (6)
  { id: 'mario-fire-form', name: 'Mario (Fire Form)', rarity: 'Legendary', color: '#fbbf24', season: 'Video Game' },
  { id: 'link-champion-form', name: 'Link (Champion Form)', rarity: 'Legendary', color: '#fbbf24', season: 'Video Game' },
  { id: 'sonic-super-sonic', name: 'Sonic (Super Sonic)', rarity: 'Legendary', color: '#fbbf24', season: 'Video Game' },
  { id: 'steve-netherite-armor', name: 'Steve (Netherite Armor)', rarity: 'Legendary', color: '#fbbf24', season: 'Video Game' },
  { id: 'pikachu-gigantamax', name: 'Pikachu (Gigantamax)', rarity: 'Legendary', color: '#fbbf24', season: 'Video Game' },
  { id: 'kirby-hypernova', name: 'Kirby (Hypernova)', rarity: 'Legendary', color: '#fbbf24', season: 'Video Game' },

  // Mythic (3)
  { id: 'mewtwo', name: 'Mewtwo', rarity: 'Mythic', color: '#f87171', season: 'Video Game' },
  { id: 'freddy-fazbear', name: 'Freddy Fazbear', rarity: 'Mythic', color: '#f87171', season: 'Video Game' },
  { id: 'fox-mccloud', name: 'Fox McCloud', rarity: 'Mythic', color: '#f87171', season: 'Video Game' },

  // Ultra Mythic (1)
  { id: 'herobrine', name: 'Herobrine', rarity: 'Ultra Mythic', color: '#ffffff', season: 'Video Game' },
];
